// This file is generated by FlutterFire CLI.
// Replace this with your actual Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgP9XU9Rtmxf5YpMn4HE372LJ-WvVM8I',
    appId: '1:689629822827:web:cf9401102c832dce82162e',
    messagingSenderId: '689629822827',
    projectId: 'street-light-monitor-dec88',
    authDomain: 'street-light-monitor-dec88.firebaseapp.com',
    storageBucket: 'street-light-monitor-dec88.firebasestorage.app',
    measurementId: 'G-CQBP0R8GE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCld2v0mntsQPfbLl1XKaRdKcilGUvwEzc',
    appId: '1:689629822827:android:d41090c6f081351882162e',
    messagingSenderId: '689629822827',
    projectId: 'street-light-monitor-dec88',
    storageBucket: 'street-light-monitor-dec88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENdf216pJGE5x57yONXzl7kg9gjbRqWA',
    appId: '1:689629822827:ios:cfb2b3c0bfdeee8982162e',
    messagingSenderId: '689629822827',
    projectId: 'street-light-monitor-dec88',
    storageBucket: 'street-light-monitor-dec88.firebasestorage.app',
    iosClientId: '689629822827-819kssoovcboouk4sce820ioakg3b32t.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringSystemForStreetLights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENdf216pJGE5x57yONXzl7kg9gjbRqWA',
    appId: '1:689629822827:ios:cfb2b3c0bfdeee8982162e',
    messagingSenderId: '689629822827',
    projectId: 'street-light-monitor-dec88',
    storageBucket: 'street-light-monitor-dec88.firebasestorage.app',
    iosClientId: '689629822827-819kssoovcboouk4sce820ioakg3b32t.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitoringSystemForStreetLights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPgP9XU9Rtmxf5YpMn4HE372LJ-WvVM8I',
    appId: '1:689629822827:web:703fc79cefde3d4f82162e',
    messagingSenderId: '689629822827',
    projectId: 'street-light-monitor-dec88',
    authDomain: 'street-light-monitor-dec88.firebaseapp.com',
    storageBucket: 'street-light-monitor-dec88.firebasestorage.app',
    measurementId: 'G-968XX77259',
  );

}